function createfigure_P3(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 21-Feb-2016 21:37:22

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',4,'FontWeight','bold',...
    'FontSize',24);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Uplink','MarkerSize',15,'Marker','square',...
    'LineWidth',5,...
    'Color',[1 0 0]);

% Create xlabel
xlabel({'Distance (m)'});

% Create ylabel
ylabel({'Reliability'});

% Create legend
legend(axes1,'show');

